# Generated by Django 5.0.4 on 2024-04-14 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0002_blockchat_title_alter_block_chat_alter_block_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='block',
            name='chat',
        ),
        migrations.AddField(
            model_name='messages',
            name='block',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='hostel.block', verbose_name='Блок'),
        ),
        migrations.DeleteModel(
            name='BlockChat',
        ),
    ]
