# Generated by Django 5.0.4 on 2024-04-14 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0004_remove_messages_block_block_messages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='messages',
        ),
        migrations.AddField(
            model_name='messages',
            name='block',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='hostel.block', verbose_name='Блок'),
        ),
    ]
