# Generated by Django 5.0.4 on 2024-04-18 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('hostel', '0005_remove_block_messages_messages_block'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Duty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsible_person', models.CharField(max_length=50, verbose_name='Ответственный человек')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('duty_date', models.DateTimeField(verbose_name='Дата дежурства')),
                ('room', models.CharField(max_length=3, verbose_name='Комната')),
                ('block', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='hostel.block', verbose_name='Блок')),
                ('sending_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(default=1, null=True)),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('content_type', models.ForeignKey(default=20, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('duty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hostel.duty', verbose_name='Дежурство')),
            ],
        ),
    ]
