# Generated by Django 5.0.4 on 2024-04-23 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0006_duty_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='photo',
            new_name='image',
        ),
    ]
