# Generated by Django 5.0.4 on 2024-04-23 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0009_remove_image_content_type_remove_image_object_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='duty',
        ),
    ]
