# Generated by Django 5.0.4 on 2024-04-23 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('hostel', '0011_image_duty'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='content_type',
            field=models.ForeignKey(default=20, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='image',
            name='object_id',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
    ]
