# Generated by Django 5.0.4 on 2024-04-23 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0012_image_content_type_image_object_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='image',
            name='object_id',
        ),
    ]
