# Generated by Django 5.0.4 on 2024-04-25 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0014_ads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Url'),
        ),
    ]
