# Generated by Django 5.0.4 on 2024-04-25 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0015_alter_ads_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ads',
            name='slug',
        ),
    ]
