# Generated by Django 5.0.4 on 2024-04-25 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0016_remove_ads_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='ImageDuty',
        ),
        migrations.CreateModel(
            name='ImageAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('ad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hostel.ads', verbose_name='Объявление')),
            ],
        ),
    ]
