# Generated by Django 5.0.4 on 2024-04-28 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0020_news_dislikes_news_likes_commentnews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='dislikes',
            field=models.IntegerField(default=0, verbose_name='Кол-во дизлайков'),
        ),
        migrations.AlterField(
            model_name='news',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='Кол-во лайков'),
        ),
        migrations.AlterField(
            model_name='news',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Кол-во просмотров'),
        ),
    ]
